### PR TITLE
Avoid column reordering when key is present

### LINKED ISSUE #199: metadata_fst inproperly displays data.table key
`fst::metadata_fst()` does not display the key of the data table correctly if the order of columns are not in alphabetical order. 

```r
library(data.table)
data <- data.table(u = 1:3, d = LETTERS[1:3], t = 0:2, key = c("u", "d"))
fst_file <- tempfile(fileext = ".fst")
fst::write_fst(data, fst_file)
fst::metadata_fst(fst_file)
#> <fst file>
#> 3 rows, 3 columns (file24454a7907b2.fst)
#> 
#> * 'u': integer (key 2)
#> * 'd': character
#> * 't': integer (key 1)
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #199.

### CODE REVIEW

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, thanks for your pull request!

Some tests are failing, because [later in the function](https://github.com/fstpackage/fst/blob/6db6a49b01f42a0a392dfdacbd872aff05e7ddf2/R/fst.R#L150), the ordering is implicitly assumed. So when we do not order when merging, the locations of the reported keys in the output are incorrect.

(also, printing the column names in the order in which they occur in the dataset might be preferable)

I can see how this design is a bit shaky, because that assumption is not documented anywhere!

**Comment by MarcusKlik** [comment]
Would it be preferable to display the key-columns first and then the other columns in their original order?

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, I've adapted your code slightly to display the key columns first and below that the other columns in the original order (also when that ordering is not alphabetically :-)).

thanks a lot for the pull request!

**Comment by renkun-ken** [comment]
Thanks!

**Pull request merged**
